on:
  push:
    tags:
      - v*.*.*
  pull_request:
    branches: [master]
    
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Dockerpush
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Print Env
        run: |-
          echo ${GITHUB_REF#refs/*/}
        
      - name: Print tag
        run: |-
          echo $(git tag)
