on:
  push:
  pull_request:
    branches: [master]
    
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Dockerpush
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Print Env
        run: |-
          echo ${GITHUB_REF#refs/*/}
      
      - name: Get image version
        run: |-
          image_version=$(grep "image" version | awk '{print $2}')
          echo "::set-output name=IMAGE_VERSION::$(echo $image_version)"
        id: image-version

      - name: Print image_version
        run: echo "${{ steps.image-version.outputs.IMAGE_VERSION }}"

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Docker login
        run: gcloud --quiet auth configure-docker

      - name: Docker build image
        run: docker build -t "${{ steps.image-version.outputs.IMAGE_VERSION }}" .

      - name: Docker push image
        run: docker push "${{ steps.image-version.outputs.IMAGE_VERSION }}"
